spring:
  datasource:
    url: jdbc:h2:mem:student_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
   #enabling the H2 console
  h2:
    console:
      enabled: true
#logging:
#  level:
#    root: debug